config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :requests
  resources :departments

  root 'requests#index'
end

app/models/concerns/user_permissions.rb
module UserPermissions
  extend ActiveSupport::Concern

  def admin?
    role == 'Admin'
  end

  def agent?
    role == 'Agent'
  end

  def customer?
    role == 'Customer'
  end

  def can_access?(resource)
    return true if admin?
    case resource.class.to_s
    when 'Request'
      (department_id == resource.department_id) || (id == resource.requested_by)
    when 'User'
      id == resource.id
    end
  end

  def accessible_users
    case role
    when 'Admin'
      User.all
    when 'Agent'
      department_users
    when 'Customer'
      [self]
    end
  end

  def accessible_requests
    case role
    when 'Admin'
      Request.all
    when 'Agent'
      department_requests
    when 'Customer'
      my_requests
    end
  end

  def accessible_departments
    agent? ? [department] : Department.all
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
  # Validations
  validates :name, presence: true, uniqueness: true, length: { in: 2..32 }

  # Associations
  has_many :users, dependent: :destroy
  has_many :requests, dependent: :destroy

  # Scopes
  default_scope { order(created_at: :desc) }
end

app/models/request.rb
class Request < ActiveRecord::Base
  STATUSES = %w(Open InProgress Resolved Closed).freeze

  # Validations
  validates :title, :description, :status, :department_id, :requested_by, presence: true
  validates :status, inclusion: { in: STATUSES, message: '%{value} is not a valid Status' }
  validates :updated_by, numericality: { only_integer: true }, allow_nil: true
  validates :department_id, numericality: { only_integer: true }
  validates :requested_by, numericality: { only_integer: true }, allow_nil: true

  # Associations
  belongs_to :department
  belongs_to :requester, class_name: 'User', foreign_key: 'requested_by'
  belongs_to :updater, class_name: 'User', foreign_key: 'updated_by'

  # Callbacks
  before_save :generate_unique_id

  # Scopes
  default_scope { order(created_at: :desc) }

  # Methods
  def generate_unique_id
    next_sequential_id = if Request.order('id desc').first.try(:unique_id)
                           Request.order('id desc').first.unique_id[2..10].to_i + 1
                         else
                           1
                         end
    self.unique_id = "SR#{next_sequential_id.to_s.rjust(8, '0')}"
  end

  def fix_updated_by(user_id)
    self.updated_by = user_id
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include UserPermissions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, :rememberable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :validatable
  DEPARTMENTS = ['Debit Cards', 'Credit Cards', 'Online Banking', 'Mobile Banking', 'Loans'].freeze
  ROLES = %w(Admin Agent Customer).freeze

  # Validations
  validates :first_name, presence: true, length: { in: 2..32 }
  validates :last_name, length: { in: 2..32 }, allow_nil: true
  validates :email, presence: true, uniqueness: true
  validates :department_id, presence: false, allow_nil: true, unless: :agent?
  validates :department_id, presence: true, numericality: { only_integer: true }, allow_nil: false, if: :agent?
  validates :role, presence: true, inclusion: { in: ROLES, message: '%{value} is not a valid Role' }

  # Associations
  belongs_to :department
  has_many :my_requests, class_name: 'Request', foreign_key: :requested_by

  delegate :requests, to: :department, prefix: true, allow_nil: true
  delegate :users, to: :department, prefix: true, allow_nil: true

  # Scopes
  default_scope { order(created_at: :desc) }
  ROLES.each do |user_role|
    scope user_role.downcase.pluralize.to_sym, -> { where(role: user_role) }
  end

  # Methods
  def full_name
    first_name + ' ' + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  private

  def check_access_and_redirect(resource)
    return true if current_user.can_access?(resource)
    redirect_to requests_path, alert: 'You do not have previleges to perform this Action!'
  end

  def set_flash(resource, is_delete)
    flash_type, message = fix_type_and_messae(resource, is_delete)
    flash.now[flash_type] = message
  end

  def fix_type_and_messae(resource, is_delete)
    act = is_delete ? 'Deleted' : 'Saved'
    if resource.errors.blank?
      flash_type = :notice
      message = "#{resource.class} #{act} Successfully"
    else
      flash_type = :alert
      message = "Errors: #{resource.errors.full_messages.join(', ')}"
    end
    [flash_type, message]
  end

  # Check access and redirect users who do not have previleges
  def check_admin_access
    return true if current_user.admin?
    redirect_to requests_path, alert: 'You do not have previleges to perform this Action!'
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  before_action :check_admin_access

  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
  end

  def edit
  end

  def create
    @department = Department.new(department_params)
    @department.save
    set_flash(@department, false)
  end

  def update
    @department.update(department_params)
    set_flash(@department, false)
  end

  def destroy
    @department.destroy
    set_flash(@department, true)
  end

  private

  def set_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:name)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :check_user_access, only: [:show, :edit, :update, :destroy]

  def index
    @requests = current_user.accessible_requests
  end

  def show
  end

  def new
    @request = Request.new
  end

  def edit
  end

  def create
    @request = Request.new(request_params)
    @request.fix_updated_by(current_user.id)
    @request.save
    set_flash(@request, false)
  end

  def update
    @request.fix_updated_by(current_user.id)
    @request.update(request_params)
    set_flash(@request, false)
  end

  def destroy
    @request.destroy
    set_flash(@request, true)
  end

  private

  # Check access and redirect users who do not have previleges
  def check_user_access
    check_access_and_redirect(@request)
  end

  def set_request
    @request = Request.find(params[:id])
  end

  def request_params
    params.require(:request).permit(:title, :description, :status, :unique_id, :department_id, :requested_by,
      :updated_by)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_admin_access, except: [:show, :edit, :update]
  before_action :check_user_access, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
    set_flash(@user, false)
  end

  def update
    @user.update_without_password(user_params)
    set_flash(@user, false)
  end

  def destroy
    @user.destroy
    set_flash(@user, true)
  end

  private

  def check_user_access
    check_access_and_redirect(@user)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :department_id, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def accessible_departments_for_select
    current_user.accessible_departments.collect{|dept| [dept.name, dept.id]}
  end

  def accessible_users_for_select
    current_user.accessible_users.collect{|user| [user.full_name, user.id]}
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/departments/_form.html.haml
= form_for(department, remote: true, html: { class: 'form-horizontal' }) do |f|
  - if department.errors.any?
    #error_explanation
      %h2
        = pluralize(department.errors.count, "error")
        prohibited this department from being saved:
      %ul
        - department.errors.full_messages.each do |message|
          %li= message

  .form-group.required
    %label.col-sm-2.control-label Title
    .col-sm-10
      = f.text_field :name, placeholder: 'Name', class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Save', class: 'btn btn-primary btn-xs'
      = link_to 'Cancel', department_path(department), remote: true, class: 'btn btn-default btn-xs' unless department.new_record?

app/views/departments/_index.html.haml
.col-sm-2.sidenav
  .list-group#item_list_container.item-list-container
    = render partial: 'departments/list', locals: { departments: @departments }
.col-sm-8.text-left#item_detail.item-detail
  - if @departments.present?
    = render partial: 'departments/item', locals: { department: @departments.first }
  - else
    %p
      There are no Departments.

app/views/departments/_item.html.haml
.page-right-container
  - if notice.present?
    %p#notice.alert.alert-success= notice
  %p
    %strong Name:
    = department.name
  = link_to 'Edit', edit_department_path(department), remote: true, class: 'btn btn-primary btn-xs'
  = link_to 'Delete', department_path(department), remote: true, method: :delete, class: 'btn btn-danger btn-xs'

app/views/departments/_list.html.haml
= link_to '<span class="glyphicon glyphicon-plus"></span> New Department'.html_safe, new_department_path, remote: true,
  class: 'list-group-item list-group-item-info', id: 'new_department'
#item_list.item-list
  - departments.each do |department|
    = render partial: 'list_item', locals: { department: department }

app/views/departments/_list_item.html.haml
= link_to department.name, department_path(department), remote: true, class: 'list-group-item',
  id: "department_list_item_#{department.id}"

app/views/departments/create.js.haml
- render_partial = @department.errors.blank? ? 'departments/item' : 'departments/form'
$('#item_detail').html("#{ escape_javascript(render(partial: render_partial, locals: { department: @department })) }");
- if @department.errors.blank?
  $('#item_list').prepend("#{ escape_javascript(render(partial: 'list_item', locals: { department: @department })) }");

app/views/departments/destroy.js.haml
$("#department_list_item_#{@department.id}").remove();
$('#item_detail').html("#{ escape_javascript(render(partial: 'departments/item', locals: { department: Department.first })) }");

app/views/departments/edit.js.haml
$('#item_detail').html("#{ escape_javascript(render(partial: 'form', locals: { request: @request })) }");

app/views/departments/index.js.haml
$('#layout_page').html("#{ escape_javascript(render(partial: 'departments/index', locals: { departments: @departments })) }");

app/views/departments/new.js.haml
$('#item_detail').html("#{ escape_javascript(render(partial: 'form', locals: { department: @department })) }");

app/views/departments/show.js.haml
$('#item_detail').html("#{ escape_javascript(render(partial: 'departments/item', locals: { department: @department })) }");

app/views/departments/update.js.haml
- render_partial = @department.errors.blank? ? 'departments/item' : 'departments/form'
$('#item_detail').html("#{ escape_javascript(render(partial: render_partial, locals: { department: @department })) }");
- if @department.errors.blank?
  $("#department_list_item_#{@department.id}").replaceWith("#{ escape_javascript(render(partial: 'list_item', locals: { department: @department })) }");

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    - if user_signed_in?
      .navbar-header
        %button.navbar-toggle{"data-target" => "#myNavbar", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to 'Home', requests_path, class: 'navbar-brand'
      #myNavbar.collapse.navbar-collapse
        %ul.nav.navbar-nav.header-nav
          %li.active
            = link_to "Requests", requests_path
          %li
            = link_to "Profile", user_path(current_user), remote: true
          - if current_user.admin?
            %li
              = link_to "Departments", departments_path, remote: true
            %li
              = link_to "Users", users_path, remote: true
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to "<span class='glyphicon glyphicon-log-out'></span> Logout".html_safe,
              destroy_user_session_path, method: :delete

app/views/layouts/_sub_header.haml
.navbar-xs
  .navbar-primary
    %nav.navbar.navbar-static-top{:role => "navigation"}
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-8", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        / %a.navbar-brand{:href => "#"} Brand
      / Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-8.collapse.navbar-collapse
        %h4#sub_header.text-center.sub-header
          Requests

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SupportSystem
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: 'layouts/header'
    .container-fluid.text-center.layout-container
      - if user_signed_in?
        = render partial: 'layouts/sub_header'
      = yield

    %footer.container-fluid.text-center
      %p Customer Support System

app/views/requests/_form.html.haml
= form_for(request, remote: true, html: { class: 'form-horizontal' }) do |f|
  - if request.errors.any?
    #error_explanation
      %h2
        = pluralize(request.errors.count, "error")
        prohibited this request from being saved:
      %ul
        - request.errors.full_messages.each do |message|
          %li= message

  .form-group.required
    %label.col-sm-2.control-label Title
    .col-sm-10
      = f.text_field :title, placeholder: 'Title', class: 'form-control'
  .form-group.required
    %label.col-sm-2.control-label Description
    .col-sm-10
      = f.text_area :description, placeholder: 'Description', class: 'form-control'
  .form-group.required
    %label.col-sm-2.control-label Status
    .col-sm-10
      = f.select :status, Request::STATUSES, {}, { class: 'form-control' }
  .form-group.required
    %label.col-sm-2.control-label Department
    .col-sm-10
      = f.select :department_id, accessible_departments_for_select, {}, { class: 'form-control' }
  .form-group.required
    %label.col-sm-2.control-label Requested By
    .col-sm-10
      = f.select :requested_by, accessible_users_for_select, {}, { class: 'form-control' }
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Save', class: 'btn btn-primary btn-xs'
      = link_to 'Cancel', request_path(request), remote: true, class: 'btn btn-default btn-xs' unless request.new_record?

app/views/requests/_index.html.haml
= link_to '<span class="glyphicon glyphicon-plus"></span> New Request'.html_safe, new_request_path, remote: true,
  class: 'list-group-item list-group-item-info', id: 'new_request'
#item_list.item-list
  - requests.each do |request|
    = render partial: 'list_item', locals: { request: request }

app/views/requests/_item.html.haml
.page-right-container
  - if notice.present?
    %p#notice.alert.alert-success= notice
  %p
    %strong Title:
    = request.title
  %p
    %strong Description:
    = request.description
  %p
    %strong Status:
    = request.status
  %p
    %strong Unique:
    = request.unique_id
  %p
    %strong Department:
    = Department.find(request.department_id).try(&:name)
  %p
    %strong Requested by:
    = User.find(request.requested_by).try(&:full_name)
  %p
    %strong Updated by:
    = request.updated_by
  = link_to 'Edit', edit_request_path(request), remote: true, class: 'btn btn-primary btn-xs'
  = link_to 'Delete', request_path(request), remote: true, method: :delete, class: 'btn btn-danger btn-xs'

app/views/requests/_list.html.haml
= link_to '<span class="glyphicon glyphicon-plus"></span> New Request'.html_safe, new_request_path, remote: true,
  class: 'list-group-item list-group-item-info', id: 'new_request'
#item_list.item-list
  - requests.each do |request|
    = render partial: 'list_item', locals: { request: request }

app/views/requests/_list_item.html.haml
= link_to request.title, request_path(request), remote: true, class: 'list-group-item',
  id: "request_list_item_#{request.id}"

app/views/requests/create.js.haml
- render_partial = @request.errors.blank? ? 'requests/item' : 'requests/form'
$('#item_detail').html("#{ escape_javascript(render(partial: render_partial, locals: { request: @request })) }");
- if @request.errors.blank?
  $('#item_list').prepend("#{ escape_javascript(render(partial: 'list_item', locals: { request: @request })) }");

app/views/requests/destroy.js.haml
$("#request_list_item_#{@request.id}").remove();
$('#item_detail').html("#{ escape_javascript(render(partial: 'requests/item', locals: { request: Request.first })) }");

app/views/requests/edit.js.haml
$('#resource_detail').html("#{ escape_javascript(render(partial: 'form', locals: { request: @request })) }");

app/views/requests/index.html.haml
.row.content.layout-page#layout_page
  .col-sm-2.sidenav
    .list-group#item_list_container.item-list-container
      = render partial: 'requests/list', locals: { requests: @requests }
  .col-sm-8.text-left#item_detail.item-detail
    - if @requests.present?
      = render partial: 'requests/item', locals: { request: @requests.first }
    - else
      %p
        There are no Requests.

app/views/requests/new.js.haml
$('#item_detail').html("#{ escape_javascript(render(partial: 'form', locals: { request: @request })) }");

app/views/requests/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @request.title
%p
  %strong Description:
  = @request.description
%p
  %strong Status:
  = @request.status
%p
  %strong Unique:
  = @request.unique_id
%p
  %strong Department:
  = @request.department_id
%p
  %strong Requested by:
  = @request.requested_by
%p
  %strong Updated by:
  = @request.updated_by
= link_to 'Edit', edit_request_path(@request)
|
\#{link_to 'Back', requests_path}

app/views/requests/show.js.erb
$('#resource_detail').html("#{ escape_javascript(render(partial: 'requests/item', locals: { request: @request })) }");

app/views/requests/show.js.haml
$('#resource_detail').html("#{ escape_javascript(render(partial: 'requests/item', locals: { request: @request })) }");

app/views/requests/update.js.haml
- render_partial = @request.errors.blank? ? 'requests/item' : 'requests/form'
$('#item_detail').html("#{ escape_javascript(render(partial: render_partial, locals: { request: @request })) }");
- if @request.errors.blank?
  $("#request_list_item_#{@request.id}").replaceWith("#{ escape_javascript(render(partial: 'list_item', locals: { request: @request })) }");

app/views/users/_form.html.haml
= form_for(@user, remote: true, html: { class: 'form-horizontal' }) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this request from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .form-group.required
    %label.col-sm-2.control-label First Name
    .col-sm-10
      = f.text_field :first_name, placeholder: 'First Name', class: 'form-control'
  .form-group
    %label.col-sm-2.control-label Last Name
    .col-sm-10
      = f.text_field :last_name, placeholder: 'Last Name', class: 'form-control'
  .form-group.required
    %label.col-sm-2.control-label Email
    .col-sm-10
      = f.text_field :email, placeholder: 'Email', class: 'form-control'
  .form-group
    %label.col-sm-2.control-label Password
    .col-sm-10
      = f.password_field :password, class: 'form-control'
  .form-group.required
    %label.col-sm-2.control-label Role
    .col-sm-10
      = f.select :role, User::ROLES, {}, { class: 'form-control' }
  .form-group.required
    %label.col-sm-2.control-label Department
    .col-sm-10
      = f.select :department_id, accessible_departments_for_select, {}, { class: 'form-control' }
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Save', class: 'btn btn-primary btn-xs'
      = link_to 'Cancel', user_path(user), remote: true, class: 'btn btn-default btn-xs' unless user.new_record?

app/views/users/_index.html.haml
.col-sm-2.sidenav
  .list-group#item_list_container.item-list-container
    = render partial: 'users/list', locals: { users: users }
.col-sm-10.text-left#item_detail.item-detail
  - if users.present?
    = render partial: 'users/item', locals: { user: users.first }
  - else
    %p
      There are no Users.

app/views/users/_item.html.haml
.page-right-container
  - if notice.present?
    %p#notice.alert.alert-success= notice
  %p
    %strong First Name:
    = user.first_name
  %p
    %strong Last Name:
    = user.last_name
  %p
    %strong Email:
    = user.email
  %p
    %strong Department:
    = user.department_id.present? ? Department.find(user.department_id).try(:name) : '-'
  %p
    %strong Role:
    = user.role
  = link_to 'Edit', edit_user_path(user), remote: true, class: 'btn btn-primary btn-xs'
  = link_to 'Delete', user_path(user), remote: true, method: :delete, class: 'btn btn-danger btn-xs' unless current_user.id == user.id

app/views/users/_list.html.haml
= link_to '<span class="glyphicon glyphicon-plus"></span> New User'.html_safe, new_user_path, remote: true,
  class: 'list-group-item list-group-item-info', id: 'new_user'
#item_list.item-list
  - users.each do |user|
    = render partial: 'list_item', locals: { user: user }

app/views/users/_list_item.html.haml
= link_to user.full_name, user_path(user), remote: true, class: 'list-group-item',
  id: "user_list_item_#{user.id}"

app/views/users/create.js.haml
- render_partial = @user.errors.blank? ? 'users/item' : 'users/form'
$('#item_detail').html("#{ escape_javascript(render(partial: render_partial, locals: { user: @user })) }");
- if @user.errors.blank?
  $('#item_list').prepend("#{ escape_javascript(render(partial: 'list_item', locals: { user: @user })) }");

app/views/users/destroy.js.haml
$("#user_list_item_#{@user.id}").remove();
$('#item_detail').html("#{ escape_javascript(render(partial: 'users/item', locals: { user: User.first })) }");

app/views/users/edit.js.haml
$('#item_detail').html("#{ escape_javascript(render(partial: 'form', locals: { request: @request })) }");

app/views/users/index.js.haml
$('#layout_page').html("#{ escape_javascript(render(partial: 'users/index', locals: { users: @users })) }");

app/views/users/new.js.haml
$('#item_detail').html("#{ escape_javascript(render(partial: 'form', locals: { user: @user })) }");

app/views/users/show.js.haml
$('#item_detail').html("#{ escape_javascript(render(partial: 'users/item', locals: { user: @user })) }");

app/views/users/update.js.haml
- render_partial = @user.errors.blank? ? 'users/item' : 'users/form'
$('#item_detail').html("#{ escape_javascript(render(partial: render_partial, locals: { user: @user })) }");
- if @user.errors.blank?
  if($("#user_list_item_#{@user.id}").length > 0){
  $("#user_list_item_#{@user.id}").replaceWith("#{ escape_javascript(render(partial: 'list_item', locals: { user: @user })) }");
  }